version: "3"
services:
  api:
    build:
      context: apps/api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      ENV: development
      DB_HOST: database
    volumes:
      - ./apps/api/src:/api/src
    depends_on:
      - database
    
  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: pizza_db
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres

volumes:
  postgres: