INSERT INTO pizzas (
        name,
        size,
        price,
        image_url
    )
VALUES (
        'Margharitta',
        'small',
        20.99,
        'https://pizza.com/pizza.png'
    ),
    (
        'Margharitta',
        'medium',
        23.99,
        'https://pizza.com/pizza.png'
    ),
    (
        'Margharitta',
        'large',
        25.99,
        'https://pizza.com/pizza.png'
    ), (
        'Pepperoni',
        'small',
        20.99,
        'https://pizza.com/pizza.png'
    ),
    (
        'Pepperoni',
        'medium',
        23.99,
        'https://pizza.com/pizza.png'
    ),
    (
        'Pepperoni',
        'large',
        25.99,
        'https://pizza.com/pizza.png'
    ), (
        'Carbonara',
        'small',
        20.99,
        'https://pizza.com/pizza.png'
    ),
    (
        'Carbonara',
        'medium',
        23.99,
        'https://pizza.com/pizza.png'
    ),
    (
        'Carbonara',
        'large',
        25.99,
        'https://pizza.com/pizza.png'
    );